#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d dashboard web terminal code office windows .  

bspc monitor HDMI-1-0 -d 1 2 3 4 5 6 
bspc monitor eDP1 -d 7 8
#bspc monitor virtual -d 7 8 bspc monitor VIRTUAL2 -d 9 

bspc config border_width         3
bspc config focused_border_color 	'#ffa500'
bspc config normal_border_color	'#000000'
bspc config window_gap          10
bspc config border_radius	12
#bspc config top_padding		10
bspc config bottom_padding	0
bspc config left_padding 	0
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a ksnip state=floating

dbus-update-activation-environment --all
gnome-keyring-daemon --start --components=secrets
feh --bg-fill $HOME/Pictures/Wallpapers/naruto-kyubi-black.png  
wal -R & 
$HOME/.config/polybar/launch.sh &
#kilall tint2 
#tint2 -c ~/.config/tint2/eyecandy-vertical-dark.tint2rc &
HK_ROFI_MOD=vertical
#$HOME/bspwm/script/transparent_border.sh &
killall ddeadd-notification-cente & deadd-notification-center &
wmname compiz &
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
# picom  --experimental-backends &
# picom -b
nm-applet &
xinput --set-prop "USB OPTICAL MOUSE " "libinput Accel Speed" "-0.7" &
#$HOME/.config/bspwm/spawn-widget-abu.sh &
alias iproute2=iproute
lxpolkit &
xinput set-prop 15 "libinput Tapping Enabled" 1  
greenclip daemon &
